Update main.lua
thelindat/esx_multicharacter pull request #27
Opened 2021-07-18 12:43 UTC by Jye-AU

Loads NUI once screen faded out

2021-07-18 22:08 UTC, Ruqen commented on client/main.lua
> +		while screenFadedIn == false do
while not screenFadedIn

makes more sense

2021-07-20 00:15 UTC, Slypher requested changes

2021-07-20 00:15 UTC, Slypher commented on client/main.lua
> +		while screenFadedIn == false do
```lua
while not screenFadedIn do
```

2021-07-26 11:11 UTC, thelindat commented
Not necessary.

2021-07-26 11:11 UTC, closed without merging